# Generated by Django 3.1.5 on 2021-01-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='matnpayam',
            field=models.TextField(max_length=50000),
        ),
    ]
